apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth
          env:
            #The env variable name is what we see in auth service when we do process.env.JWT_KEY
            - name: JWT_KEY
              #Get the value of the env from
              valueFrom:
                #Secret key we would have created
                secretKeyRef:
                  #Name of the secret key we used
                  name: jwt-secret
                  #Inside a secret there may be many key-value pair of secrets hence provide the key name
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: auth-clu-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      targetPort: 3000
      port: 3000
