apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: tickets
          env:
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_URL
              value: 'http://nats-clu-srv:4222'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: 'mongodb://tickets-db-clu-srv:27017/tickets'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

#Cluster Service to interact with other services
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-clu-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      targetPort: 3000
      port: 3000
